server:
  port: 8080
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  config:
    import:
      - classpath:/db-config.yaml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    org.sringframework.boot: DEBUG
    org.sringframework.security: DEBUG
    com.a304.intagral: DEBUG